version: "3.9"

services:
  auth-postgres:
    container_name: auth-postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  task-postgres:
    container_name: task-postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - task_postgres_data:/var/lib/postgresql/data
      
  notification-postgres:
    container_name: notification-postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - notification_postgres_data:/var/lib/postgresql/data

volumes:
  auth_postgres_data:
  task_postgres_data:
  notification_postgres_data: